spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://34.139.156.166/mutantsbd
    username: root
    password: springroot
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true